[package]
name = "chainsight-cdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
candid = "0.8"
derive_more = "0.99.17"
ic-cdk = "0.8.1"
ic-solidity-bindgen = "0.1.5"
ic-stable-memory = "0.4.4"
ic-stable-structures = "0.5.4"
ic-web3-rs = "0.1.1"
primitive-types = "0.12.1"
serde = "1.0.163"
uuid = { version = "1.2.2", features = ["v4", "serde"] }
getrandom = { version = "0.2", features = ["js"] }
