[workspace]
members = ["chainsight-cdk", "chainsight-cdk-macros"]

[workspace.dependencies]
anyhow = "1.0.75"
candid = "0.8.4"
ethabi = "18.0.0"
futures = "0.3.28"
ic-cdk = "0.8.1"
ic-web3-rs = "0.1.2"
serde = "1.0.163"
serde_json = "1.0.107"
syn = "2.0.38"
