[workspace]
members = ["chainsight-cdk", "chainsight-cdk-macros"]

[workspace.dependencies]
anyhow = "1.0.75"
candid = { version = "^0.9.6", features = ["parser"] }
ethabi = "18.0.0"
futures = "0.3.28"
ic-cdk = "^0.11"
ic-web3-rs = { git = "https://github.com/horizonx-tech/ic-web3-rs.git", branch = "topic/ic-cdk-0.11" }
ic-solidity-bindgen = { git = "https://github.com/horizonx-tech/ic-solidity-bindgen.git", branch = "topic/ic-cdk-0.11" }
serde = "1.0.163"
serde_json = "1.0.107"
syn = "2.0.38"
