// NOTE: generated by CanisterMethodIdentifier.compile
#![allow(dead_code, unused_imports)]
use candid::{self, CandidType, Decode, Deserialize, Encode, Principal};
#[derive(
    Clone,
    Debug,
    candid :: CandidType,
    candid :: Deserialize,
    serde :: Serialize,
    chainsight_cdk_macros :: StableMemoryStorable,
)]
pub struct ResponseType {
    value: String,
    timestamp: u64,
}
